---
title: "Mod 4 data viz"
output: html_document
date: "2025-04-05"
---

```{r}
## Load packages ####
library(tidyverse)
```

```{r}
## Load data:####
mpg
# Data includes dsp (engine size of the cars in litres) and hwy (car's fuel efficiency in miles per galon)
# A car with a low fuel efficiency consumes more fuel than a car with a high fuel efficiency when they travel the same distance.

```
```{r}
## Create fisrt ggplot####
ggplot(data = mpg) + 
  geom_point(mapping = aes(x= displ, y=hwy))
# ggplot() creates a coordinate system that you add layers to.
# The first argument of ggplot() is the dataset to use in the graph. 
# ggplot(data = mpg) creates an empty graph.
# To complete the graph you need to add one or more layers to ggplot():
# The function geom_point() adds a layer of points to the plot, which creates a scatter plot.
# Each geom function in ggplot2 takes a mapping argument. This defines how variables in your dataset are mapped to visual properties. The mapping argument is always paired with aes(), and the x and y arguments of aes() specify which variables to map to the x and y axes. ggplot2 looks for the mapped variables in the data argument, in this case, mpg.

```
# Plot shows a negative relationship bewteen the engine size and the fuel efficiency
```{r}
# Understanding the grammar of graphics####
# use this template as a reference to develop plots:
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION> (mapping = aes (<MAPPINGS>))

# Make an empty ggplot(); this provides the coordinate system that the remainder of ggplot2 arguments can be mapped to. 
ggplot () # Creates an empty plot

ggplot (data = mpg)# This also creates a plot window (an empty plot) because there is no data argument; the plot window has not yet applied any axis limits

```
 
```{r}
# Aestethic Mapping: Class to colour####

# In addition to simply plotting coordinates of x, y data, you can add a third variable, such as class, by mapping it to an aesthetic represented as aes() in the template above.

# An aesthetic  is a visual property of the objects you’ve already plotted, and can include things like: size, shape, and colour> 

# So when plotting, you need twho attributes: a geom and aesthetics. 

# You can convey information about your data by mapping the aesthetics in your plot to the variables in your dataset. For example, you can map the colors of your points to the class variable to reveal the class of each car.

# To map an aesthetic to a variable, associate the name of the aesthetic to the name of the variable inside aes(). ggplot2 will automatically assign a unique level of the aesthetic to each unique value of the variable.

# Let's do an excercise to explore aestethic mapping: 
#1. Change point colour by class:

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, colour=class))
```
# This mapped class to colour.
```{r}
# Aestethic Mapping: Point size by class####

# Now, lets map o the size aesthetic in the same way as class to colour.

# Change point transparency by class (alpha). Here the alpha aesthetic is what dictates the transparency.

# Consider trying a simple number, like 0.3 to this aesthetic, which globally applies a transparency to all points. This is very helpful for dense point clouds, where you want a reader to see that there are overlapping data points. 

#Change point size by class:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```
# Note how the sizes of the points now represent the class of car. Also note how ggplot2 gives you at least a little bit of guidance about what makes good data visualisation. Look at the warning messsage; using alpha for a discrete variable is not advised
```{r}
# Changing propertiies manually####

# Change properties manually, such as by offering a number or a colour. Let’s make all of our points blue:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color="blue")

# There are a range of manual aesthetics you can set to manually alter the appearance of your plot. These include: The name of a color as a character string, the size of a point in mm, and the shape of a point as a number

```

```{r}
# Practice Question####
# 1. What happens if you map an aesthetic to something other than a variable name, like aes(colour = displ < 5)? Note, you’ll also need to specify x and y.

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, colour = displ < 5))

#This will color points based on whether displ is less than 5. displ < 5 evaluates to TRUE or FALSE, so ggplot will color the points differently for each value.

# Points with displ < 5 will be one color (red)
# Points with displ >= 5 will be another (blue)
```
```{r}
# Troubleshooting####
# As with all programming you’ll run into some problems. But that’s OK! It’s very common for data scientists or analysts to have to keep testing and trying 

# Example:
ggplot(data = mpg) 
+ geom_point(mapping = aes(x = displ, y = hwy)) 
# the + should be on top line
```

```{r}
# Facet and panel plots: Facet_wrap ####

# As seen in any scientific literature with figures, a common practice is to break a single complex plot into many sub plots (or panels). This allows you to develop separate plots for a range of reasons, most often to show a subset of your data. 

# In ggplot2, you can do this by using facets 

# To facet your plot using a single variable, use facet_wrap(). Facet wrap syntax is in the function of a formula (kind of like a linear model formula), where the ~ dictates which variable you want to subset your data with.

# Note: only use facet_wrap() for discrete variables.

# Let's try it:
 ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~class, nrow = 2)
```
```{r}
# Facet and panel plots: Facet_grid ####

# To facet with more than one variable, then use facet_grid(). Here you need two variables using ~ to split them up.

# Facet plot on the combination of two variables using facet_grid(). Facet grid needs two variables separated by a ~

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv~cyl)

# Use a . if you do not want to facet in the rows or column dimension. Note what happens in this case:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(.~cyl)

```
```{r}
# Practice question####

# Read ?facet_wrap. What does nrow do? What does ncol do? What other options control the layout of the individual panels?

# nrow sets the number of rows of panels in your facet layout.
# ncol sets the number of columns of panels.

# scales: control wheter axes are shared or free across panels:
# "fixed" (default): All panels have the same x and y scales.
# free: Each panel gets its own x and y scale.
# free_x: Only x scales are allowed to vary.
# free_y: Only y scales are allowed to vary.

# dir:Controls the direction in which the panels are filled:
# h (horizontal, default): Fills row-wise
# v (vertical): Fills column-wise

# strip.position: Controls where the facet labels appear:
# "top", "bottom", "left", "right"

# as.table: Logical (default TRUE). If TRUE, the facet layout starts from the top-left; if FALSE, it starts from the bottom-left (like a standard graphing layout).
```

```{r}
# Fitting Simple lines ####

# With ggplot2 you can use a variety of visual objects to represent your data. So far we have used points that are plotted at the coordinate location of the x and y axes for each data point.

# To display data as points, use geom_point():
ggplot(data = mpg) +
  geom_point(mapping = aes( x = displ, y = hwy))

# ggplot2 can use a variety of geom objects to represent the data. Here, we might want to use bar plots, line charts, boxplots and so on. Well we can handle this issue in ggplot directly using a different geom to plot the same data.

# To display the same data as a smooth line fit through the points use geom_smooth().
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))

# Recap: A geom is an object that your plot uses to represent the data. To change the geom type in your plot, simply change the geom function that you add to your plot template. 

# It is helpful to try a few things out, in which case you could use comments to help you remember what worked and what didn’t. For example:
ggplot(data = mpg) + 
#  geom_point(mapping = aes(x = displ, y = hwy)) # points horrible 
  geom_smooth(mappings = aes(x = displ, y = hwy)) # try smooth line

# You can also change the line type, and like we did with colours, you can use a variable to control it. 

# you can see we have different types of dashes when we use the linetype argument with geom_smooth(), which separate the cars into three lines based on their drv (front wheel, rear wheel or 4wd) value.

ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```
```{r}
# Grouping objects by a categorical variable####

# we will use the group argument to show that our data is in fact grouped. It won’t add a new legend but can easily be used to vary your plots by the discrete variable.

# Set the group aesthetic to a categorical variable to draw multiple objects.

ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv)) # all the lines are the same color

# Change the color of each line based on drv value:

ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )

# Lets plot multiple geoms on the single plot. All you need to do is to add them together. This one is nice for showing the underlying data and how it relates to the geom_smooth line.

ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes( x= displ, y = hwy))
# Note how the top and second rows are duplicated, meaning if you wanted to change the x variable in your plot, you’d need to change it in several locations.

# This is not ideal, and can increase the chance you’ll make an error. Therefore, ggplot allows you to pass these ‘overarching’ mappings to the ggplot() argument, making them global mappings that are applied to every single subsequent geom. Much in the same way that the data argument is also global, it is used every time a geom is called.

#Here’s an example of where we make the exact same plot as above, but it is programmatically more efficient and makes it easy for you to change a variable that you want to plot on the x or y axis. 

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth() # you can still use mappings under ggplot() to reduce duplications in code (like in the above code). This is useful if you want to change point styles or develop your own customisations. 

# Use mappings in specific layers to enable the display of different aesthetics in different layers. Note how the line is not styled by class, but you can style the points by themselves.

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth()

# The same goes if you want to specify different data for each layer. Here, we use a filter (class = "subcompact") to select a subset of the data and plot only that subset. 

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)

# Filter() shows a small subset of the dataset
```
```{r}
# Practice Question ####

# 1. What geom would you use to draw a line chart? A boxplot? A histogram? An area chart?
# Line chart: geom_line
# Boxplot: geom_boxplot
# Histogram: geom_histogram
# Area chart: geom_area

#2. Run this code in your head and predict what the output will look like. Then, run the code in R and check your predictions.

#3. Will these two graphs look different? Why/why not?

# geom_point() adds individual data points\
# geom_smooth() overlays a smoothed line (like a LOESS curve) on top of those points.The only difference is the way the data and aesthetics are passed:
# In the first plot, they’re passed globally to ggplot().
# In the second plot, they’re passed locally inside each geom_().
# They also use the same data and aesthetics.

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))

```
```{r}
# Transformation and stats####

# We are going to learn about easy transformations and data summaries using another dataset provided in ggplot2, specifically to support the teaching of transformations.  The diamonds dataset comes in ggplot2 and contains information about ~54,000 diamonds, including the price, carat, color, clarity, and cut of each diamond.

#1. Plotting Stats####

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))

# On the x-axis, the chart displays cut, a variable from the diamonds dataset. On the y-axis, it displays count, but count is not a variable in diamonds. Where does count come from? Many graphs, like scatterplots, plot the raw values of your dataset. Other graphs, like bar charts, calculate new values to plot:
# bar charts, histograms, and frequency polygons “bin” your data and then plot bin counts (the number of points that fall in each bin).
# smoothers fit a model to your data and then plot predictions from the model.
# boxplots compute a robust summary of the distribution and then display a specially formatted box.
# The algorithm used to calculate new values for a graph is called a stat, short for statistical transformation. 

# You can use geoms and stats interchangeably. For example, you can recreate the previous plot using stat_count() instead of geom_bar()

ggplot(data = diamonds) +
  stat_count(mapping = aes(x = cut))

#2. Overriding results in ggplot2####

# You might want to override a default stat now that you understand what the defaults are. Change the default stat (which is a count, a summary) to identity (which is the raw value of a variable).

demo <- tribble(
 ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)
demo

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

# You can also override a default mapping from transformed variables to aesthetics. For instance, you could display a bar chart of the proportion of your total diamond dataset rather than a count.
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = stat(prop), group = 1))
#> Warning: `stat(prop)` was deprecated in ggplot2 3.4.0.

```

```{r}
# Plotting Statistical details ####

# You might also want to show a little more about these transformations in your plot, which is good practice to be transparent about uncertainty or any other limitation of your data. 

#You can do this using stat_summary().

ggplot(data = diamonds) +
  stat_summary (
    mapping = aes( x= cut, y = depth),
    fun.min = min,
    fun.max = max, 
    fun.median = median
  )

```
```{r}
# Aesthetic Adjustments####

# A good way to boost the way you can convey information with plots using ggplot2 is to use aesthetics like colour or fill to change aspects of bar colours.
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = cut))

# Try using these aesthetics to colour by another variable like clarity. Notice how the stacking is done automatically. This is done behind the scenes with a position argument.

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity))

# The ability to make position adjustments is vital, it allows you to customise your plots in three ways, identity (raw data), fill (changes heights) and dodge (which forces ggplot2 to not put things on top of each other)

# If you use position = "identity", you will be able to place each object exactly where it falls in the context of the graph. This is vital for point charts like scatter plots but makes a mess in a bar plot situation by showing too much information (a bar plot generally summarises information). So in this case we will need to alter the bar aesthetic.

# Alter transparency (alpha)
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) +
  geom_bar(alpha = 1/5, position = "identity")

# Color the bar outlines with no fill color
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) +
  geom_bar(fill = NA, position = "identity")

# position = "fill" works like stacking, but makes each set of stacked bars the same height.
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

# position = "dodge" places overlapping objects directly beside one another
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

# jitter slightly moves points so you can see them all (especially when they overlap). 
# position = "jitter" adds a small amount of random noise to each point to avoid overplotting when points overlap. This is useful for scatterplots but not barplots.

ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
```
```{r}
# The layered grammar of graphics####

# Lets update our template for making a ggplot2. Here it is, with position adjustments, stats, and faceting 
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <FACET_FUNCTION>
```

```{r}
# Workbook Assignment####
## Load libraries
library(ggplot2)
library(dplyr)

# Create the data
damage_data <- data.frame(
  Group = c(
    "Erect Sponges", "Morel Sponges", "Finger Sponges", "Anthozoans",
    "Ophiuroids", "Echinoids", "Asteroids", "Holothurians",
    "Arthropods", "Molluscs"
  ),
  Percent_Damaged = c(
    67, NA, 10, 55, 20, 15, 1, 1, 1, 1
  ),
  Type = c(
    "Sessile", "Sessile", "Sessile", "Sessile",
    "Motile", "Motile", "Motile", "Motile",
    "Motile", "Motile"
  )
)

# Add plotting values and labels
damage_data <- damage_data %>%
  mutate(
    Plot_Value = ifelse(is.na(Percent_Damaged), 0, Percent_Damaged),
    Label = ifelse(is.na(Percent_Damaged), "No data", paste0(Percent_Damaged, "%")),
    FontStyle = ifelse(is.na(Percent_Damaged), "italic", "plain"),
    TextColor = ifelse(is.na(Percent_Damaged), "gray30", "black")
  )

# Custom color palette
palette <- c("Sessile" = "#1f78b4", "Motile" = "#33a02c")

# Plot
ggplot(damage_data, aes(x = reorder(Group, Plot_Value), y = Plot_Value, fill = Type)) +
  geom_col(width = 0.6, color = "white", linewidth = 0.2, show.legend = TRUE) +
  coord_flip() +
  geom_text(
    aes(label = Label, fontface = FontStyle, color = TextColor),
    hjust = -0.1, size = 4, show.legend = FALSE
  ) +
  scale_color_identity() +  # needed for custom text colors
  scale_fill_manual(values = palette, name = "Group Type") +
  labs(
    title = "Damage to Epifaunal Invertebrates by Trawling",
    subtitle = "Eastern Gulf of Alaska",
    x = NULL,
    y = "Percent Damaged"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.text.y = element_text(size = 11),
    axis.text.x = element_text(size = 11),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom"
  ) +
  ylim(0, 75)

```

```{r}
# Using ggplot for cummunication; labels ####

# In ggplot, you add labels with the labs() function
# Let's add a title:
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) + 
  geom_smooth(se.e = FALSE) +
  labs(title = "Fuel efficiency generally decreases with engine size")
```
```{r}
# Labels ####

# To add more text, you can use other functions:
# subtitle adds additional detail in a smaller font beneath the title and caption adds text at the bottom right of the plot 

#caption adds text at the bottom right of the plot, often used to describe the source of the data.

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  labs(
    title = "Fuel efficiency generally decreases with engine size", 
    subtitle = "Two seaters (sport cars) are an expectation because of their light weight", 
    caption = "Data from fueeleconomy.gov"
  )
```
```{r}
# Labels ####
# You can also use labs() to replace axis labels and legends titles
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_smooth (se = FALSE) +
  labs(
    x = "Engine displacement (L)",
    y = "Highway fuel economy (mpg)",
    colour = "Car type"
  )
```
```{r}
# Annotations ####
# To add text to your plots, you can use geom_text() 
best_in_class <- mpg %>%
  group_by(class) %>%
  filter(row_number(desc(hwy))==1)

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_text(aes(label = model), data = best_in_class)

# the labels overlap, but you can handle that issue if you ever find it a problem. These include a nudge() function to move your text a certain amount and using other R packages to handle text wrapping etc. 

```
```{r}
# Scales ####

# R  can automatically add labels for you:
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class))

# However, if you want to tweak them, you can offer values to the scale parameters by adding numbers in the appropriate scale arguments

# Remember that to provide limits you’ll need to offer a character vector showing the start and end of your limit (e.g. c(0,12)). Note also that: ?scale_x_continuous() has plenty of other arguments, so don’t forget to explicitly state the argument you’re providing these limits for (e.g. limits = c(0,12)). 
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  scale_x_continuous() +
  scale_y_continuous() + 
  scale_colour_discrete()
```
```{r}
# Axis ticks ####
# You can also change the ticks on your axes. Breaks controls the position of the ticks and you can use labels as an argument to change the text label associated with ticks. 

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  scale_y_continuous(breaks = seq(15, 40, by = 5))

seq(15, 40, by = 5) # This creates a sequence of number from 15 to 40, by increments of five

# You can use labels to set to NULL to suppress the labels altogether.
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(labels = NULL)

```
```{r}
# Legends and colour schemes ####
# To control the overall position of the legend, you need to use a theme() setting.
base <- ggplot(mpg, aes(displ, hwy)) +
  geom_point (aes(colour = class))

base + theme (legend.position = "left")
base + theme (legend.position = "top")
base + theme (legend.position = "bottom")
base + theme (legend.position = "right")

# You can also use legend.position = "none" to suppress the display of the legend altogether
```
```{r}
# Replacing a scale ####
# It’s very useful to plot transformations of your variables. For example, as we’ve seen in diamond prices it’s easier to see the precise relationship between carat and price if we log transform them using a ggplot2 function for scale precisely for this purpose.

ggplot(diamonds, aes(carat, price)) +
  geom_bin2d() + 
  scale_x_log10() + 
  scale_y_log10()
```
```{r}
# Colour scale ####
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv))

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv)) +
  scale_colour_brewer(palette = "Set1")
 # if there are just a few colours, you can add a redundant shape mapping. This will also help ensure your plot is interpretable in black and white.

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv, shape = drv)) +
  scale_colour_brewer(palette = "Set1")

# you can set the colours yourself, using scale_colour_manual()
presidential %>%
  mutate(id = 33 + row_number()) %>%
  ggplot(aes(start, id, colour = party)) +
    geom_point() +
    geom_segment(aes(xend = end, yend = id)) +
    scale_colour_manual(values = c(Republican = "red", Democratic = "blue"))

# One of the most popular packages is the viridis colour scheme. To use it, simply use scale_colour_viridis() provided by the viridis package
library(viridis)
library(hexbin)

df <- tibble( # note we're just making a fake dataset so we can plot it
  x = rnorm(10000),
  y = rnorm(10000)
)
ggplot(df, aes(x, y)) +
  geom_hex() + # a new geom!
  coord_fixed()

ggplot(df, aes(x, y)) +
  geom_hex() +
  viridis::scale_fill_viridis() +
  coord_fixed()

```
```{r}
# Themes ####
# you can customize the entire theme of your plot. Themes allow you to change some or all of the non-data elements of your plot with a theme.

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_light()

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_bw()

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_classic()

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_dark()

# You can also develop your own themes. For example: 
 theme (panel.border = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        legend.position="bottom",
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        panel.grid.major = element_blank(),
        legend.key = element_blank(),
        legend.background = element_blank(),
        axis.text.y=element_text(colour="black"),
        axis.text.x=element_text(colour="black"),
        text=element_text(family="Arial")) 
```
```{r}
# Saving and exporting your plots####
# Now that you've developed your plot, you want to save it to disk in some format that allows you to import it into your report or to share it with the world.  In general, the best way to make a single file will be to export it using the ggsave() function. There are two main ways to get your plots out of R using ggplot2. ggsave() will save the most recent plot to your working directory.

ggplot(mpg, aes(displ, hwy)) + geom_point()

ggsave("my-plot.pdf")
#> Saving 7 x 4.32 in image
```

```{r}
# Assignment ####
# 1. Obtain data; Go to QFISH and review all of the available datasets that you could analyse
fishing_data <- read_csv("data/Qfish.csv")
head(fishing_data)
```
```{r}
#2. Tidy the data using tidyverse:
library(tidyverse)

# Data cleaning:
fishing_data_clean$Tonnes <- gsub(",", "", fishing_data_clean$Tonnes)
fishing_data_clean$Tonnes <- as.numeric(fishing_data_clean$Tonnes)
head(fishing_data_clean)
```
```{r}
# Remove the outlier (Tonnes max value)
qfish_no_outlier <- Qfish[Qfish$Tonnes <max(Qfish$Tonnes, na.rm = TRUE),]

#Create Scatter Plot:
ggplot() +
  geom_point(data = qfish_no_outlier, aes(x = Licences, y = Tonnes, color = "Catch Data"),
      alpha = 0.8, size = 1.5) +
  geom_smooth(data = qfish_no_outlier, aes(x= Licences, y = Tonnes, colour = "Trendline"),
             method = "gam", se = FALSE, size = 1) +
  scale_color_manual(
    name = "Legend",
    values = c("Catch Data"= "darkblue", "Trendline"= "red")
  ) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.15))) +
  labs(
    title = "Relationship Between Number of Licenses and Tonnes of Catch",
    x = "Number of Licenses",
    y = "Tonnes of Catch"
  ) +
  theme_minimal()
```
```{r}
# Spatial Data ####

# install and load your packages
#load into R library
library(tidyverse)
library(sf) # simple features
library (terra) # for raster
library(tmap) # Thematic maps are geographical maps in which spatial data distributions are visualized

# 1. Download and load dataset: 
library(readr)
dat <- read_csv("data/data-for-course/copepods_raw.csv")
dat

```
```{r}

```

